### ISSUE TITLE
Move this repo to jupyter-lsp ?

### ISSUE THREAD

**Issue by martinRenou** [jupyter-lsp/json-lsp#8]
It might be worth thinking about moving this repo (and https://github.com/martinRenou/yaml-lsp?) outside of my user account, maybe https://github.com/jupyter-lsp would be a proper place?

cc. @jtpio @krassowski

**Comment by jtpio** [comment]
Sounds good to me, thanks @martinRenou!

**Comment by krassowski** [comment]
Sounds good to me too. Feel free to proceed with the transfer, and thank you!

**Comment by martinRenou** [comment]
Thanks for accepting! I will proceed with the transfer

**Comment by martinRenou** [comment]
Done :)
